#!/bin/env sh

extra_flags=
source_path=.
app_path=$source_path/app.d
exe_path=./app
parin_package_path=./parin_package
joka_package_path=./joka_package
compiler=dmd
version=linux_x86_64

[ -n "$1" ] && compiler=$1
[ -n "$2" ] && version=$2
$compiler \
    -of=$exe_path \
    -L=-L$parin_package_path/vendor/$version \
    -J=$parin_package_path/source/parin -I=$source_path -i \
    -J=./assets $extra_flags \
    $app_path
