#!/bin/env sh

# TODO: Try bulding a lib file with dub and link with with emcc.
# This will let us compile dub projects into a web game.

## A script for creating a web build.
## Just copy-paste the web folder into your project and run the script.

# The config.
output_file="./web/index.html"
shell_file="./web/shell.html"
library_file="./web/libraylib.a"

source_dir="./source"
assets_dir="./assets"

main_files="$source_dir/*.d"

# Check if things exist.
script_dir="$(dirname $0)"
cd $script_dir/..
[ ! -e "$shell_file" ] && echo "ERROR: Shell file doesn't exist." && exit 1
echo "OK: Shell file exists."
[ ! -e "$library_file" ] && echo "ERROR: Library file doesn't exist." && exit 1
echo "OK: Library file exists."
[ ! -e "$source_dir" ] && echo "ERROR: Source folder doesn't exist." && exit 1
echo "OK: Source folder exists."
[ ! -e "$assets_dir" ] && echo "ERROR: Assets folder doesn't exist." && exit 1
echo "OK: Assets folder exists."

# Build for web.
ldc2 -c -betterC -mtriple=wasm32-unknown-unknown-wasm -checkaction=halt -I$source_dir -i $main_files

if [ -z "$(ls $assets_dir)" ]; then
    emcc -o $output_file *.o $library_file -s USE_GLFW=3 -s ERROR_ON_UNDEFINED_SYMBOLS=0 --shell-file $shell_file
else
    emcc -o $output_file *.o $library_file -s USE_GLFW=3 -s ERROR_ON_UNDEFINED_SYMBOLS=0 --shell-file $shell_file --preload-file $assets_dir
fi
